#!/usr/bin/env python

import pathlib

Import("env")
module_env = env.Clone()

# Paths
module_path = pathlib.Path(Dir(".").abspath)

env.Append(LIBPATH=[module_path / "thirdparty/sentry-native/build/RelWithDebInfo"])
env.Append(LINKFLAGS=["sentry.lib"])

CPPPATH = [
"thirdparty/sentry-native/include"
]
module_env.Append(CPPPATH=CPPPATH)

# Godot source files
module_env.add_source_files(module_env.modules_sources, "*.cpp")
